"""Init

Revision ID: 8b4365dc1903
Revises: 0f9c9604e02a
Create Date: 2025-03-12 21:23:22.405709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4365dc1903'
down_revision: Union[str, None] = '0f9c9604e02a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_domain'), 'sites', ['domain'], unique=True)
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_index(op.f('ix_sites_token'), 'sites', ['token'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('page_url', sa.String(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_browser'), 'clients', ['browser'], unique=False)
    op.create_index(op.f('ix_clients_country'), 'clients', ['country'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_ip'), 'clients', ['ip'], unique=False)
    op.create_index(op.f('ix_clients_os'), 'clients', ['os'], unique=False)
    op.create_index(op.f('ix_clients_page_url'), 'clients', ['page_url'], unique=False)
    op.create_index(op.f('ix_clients_referrer'), 'clients', ['referrer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_referrer'), table_name='clients')
    op.drop_index(op.f('ix_clients_page_url'), table_name='clients')
    op.drop_index(op.f('ix_clients_os'), table_name='clients')
    op.drop_index(op.f('ix_clients_ip'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_country'), table_name='clients')
    op.drop_index(op.f('ix_clients_browser'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_sites_token'), table_name='sites')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_domain'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
