"""Updated models

Revision ID: ef5f15d84a8a
Revises: c1600e8f01bf
Create Date: 2025-03-13 08:19:44.578699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5f15d84a8a'
down_revision: Union[str, None] = 'c1600e8f01bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('visited_at', sa.Date(), nullable=True))
    op.create_index(op.f('ix_clients_visited_at'), 'clients', ['visited_at'], unique=False)
    op.add_column('pages', sa.Column('visitors', sa.Integer(), nullable=True))
    op.add_column('pages', sa.Column('views', sa.Integer(), nullable=True))
    op.drop_column('pages', 'unique_visitors')
    op.drop_column('pages', 'total_views')
    op.add_column('sites', sa.Column('visitors', sa.Integer(), nullable=True))
    op.add_column('sites', sa.Column('views', sa.Integer(), nullable=True))
    op.drop_column('sites', 'unique_visitors')
    op.drop_column('sites', 'total_views')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('total_views', sa.INTEGER(), nullable=True))
    op.add_column('sites', sa.Column('unique_visitors', sa.INTEGER(), nullable=True))
    op.drop_column('sites', 'views')
    op.drop_column('sites', 'visitors')
    op.add_column('pages', sa.Column('total_views', sa.INTEGER(), nullable=True))
    op.add_column('pages', sa.Column('unique_visitors', sa.INTEGER(), nullable=True))
    op.drop_column('pages', 'views')
    op.drop_column('pages', 'visitors')
    op.drop_index(op.f('ix_clients_visited_at'), table_name='clients')
    op.drop_column('clients', 'visited_at')
    # ### end Alembic commands ###
