name: Pytest

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: openanalytics
          POSTGRES_PASSWORD: openanalytics
          POSTGRES_DB: openanalytics
        options: --health-cmd="pg_isready -U postgres" --health-timeout=30s --health-start-period=5s --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install ".[dev]"

      - name: Run tests
        run: |
          pytest
